export const list = [
  { id: 1, task: 'Login And Register', done: true },
  { id: 2, task: 'Users List', done: true },
  { id: 4, task: 'Resource List', done: true },
  { id: 5, task: 'Netlify', done: false },
  { id: 6, task: 'Prettier', done: true },
  { id: 7, task: 'Check .gitignore', done: true },
  { id: 8, task: 'Check Repository', done: true },
  { id: 9, task: 'React Context', done: false },
  { id: 10, task: 'Fetch API or Axios', done: true },
  { id: 11, task: 'ErrorBoundary', done: true },
  { id: 12, task: 'PropTypes', done: true },
  { id: 13, task: 'React Router', done: true },
  { id: 14, task: 'HOC', done: true },
  { id: 15, task: 'CSS Modules', done: true },
  { id: 16, task: 'react-hook-form', done: true },
  { id: 17, task: 'Code Splitting', done: true },
  { id: 18, task: 'Redux and Middleware', done: false },
  { id: 19, task: 'Custom Hooks', done: true },
  { id: 20, task: 'Redux Thunk', done: false },
  { id: 21, task: 'EsLint', done: false },
  { id: 22, task: 'CSS framework', done: true },
  {
    id: 23,
    task: 'redux thunk, multiple reducer, react testing library',
    done: false,
  },
  { id: 24, task: 'useMemo, memo, useCallback', done: true },
  { id: 25, task: 'Multiple commits', done: true },
];
